name: docs

on:
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  fabrications:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: gerbers.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: jlcpcb/bom.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: jlcpcb/position.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: gerbers
        path: gerbers
