name: Fabrication

on:
  push:
    branches:
      - main
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/*'
      - 'jlcpcb/*'

env:
  KIKIT: docker run --rm -v $PWD:/pcb -w /pcb --user $UID:$GROUPS yaqwsx/kikit kikit

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: docs.kibot.yaml
        dir: docs
        schema: NightLight_ESP32.sch
        board: NightLight_ESP32.kicad_pcb

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  fabrications:
    name: Fabrication
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Export JLCPCB fabrication files
      run: |
        ${{ env.KIKIT }} fab jlcpcb --assembly --schematic NightLight_ESP32.sch --ignore J2,JP1 NightLight_ESP32.kicad_pcb SmartishLight_ESP32
        mv SmartishLight_ESP32/gerbers.zip SmartishLight_ESP32/SmartishLight_ESP32_${{ github.run_number }}.zip

    - name: Export JLCPCB fabrication files (tall)
      run: |
        ${{ env.KIKIT }} fab jlcpcb --assembly --schematic NightLight_ESP32.sch --ignore J2,JP1 NightLight_ESP32_tall.kicad_pcb SmartishLight_ESP32_tall
        mv SmartishLight_ESP32_tall/gerbers.zip SmartishLight_ESP32_tall/SmartishLight_ESP32_tall_${{ github.run_number }}.zip

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: SmartishLight_ESP32
        path: |
          SmartishLight_ESP32/*.zip
          SmartishLight_ESP32/*.csv
          SmartishLight_ESP32_tall/*.zip
          SmartishLight_ESP32_tall/*.csv

  release:
    runs-on: ubuntu-latest
    needs: 
      - docs
      - fabrications

    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download the built assets
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Package up the combined assets
      run: |
        ls -l artifacts

    - name: Upload assets to latest release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          artifacts/*
