name: validate

on:
  push:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.1
      with:
      # Required - kibot config file
        config: report.kibot.yaml
